openapi: 3.0.0
info:
  title: Drip Store API
  version: 1.0.0
  description: API para gerenciamento de loja online Drip Store
servers:
  - url: http://localhost:3000/v1
    description: Servidor local de desenvolvimento

paths:
  /user/{id}:
    get:
      summary: Obter usuário por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Usuário encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  firstname:
                    type: string
                  surname:
                    type: string
                  email:
                    type: string
                    format: email
        '404':
          description: Usuário não encontrado
          content:
            text/plain:
              schema:
                type: string
                example: Usuário não encontrado

    put:
      summary: Atualizar usuário
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                firstname:
                  type: string
                surname:
                  type: string
                email:
                  type: string
                  format: email
      responses:
        '204':
          description: Atualização realizada com sucesso
        '400':
          description: Dados inválidos
        '401':
          description: Token faltando ou inválido
        '404':
          description: Usuário não encontrado

    delete:
      summary: Deletar usuário
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      security:
        - bearerAuth: []
      responses:
        '204':
          description: Usuário deletado com sucesso
        '401':
          description: Token faltando ou inválido
        '404':
          description: Usuário não encontrado

  /user:
    post:
      summary: Criar usuário
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - firstname
                - surname
                - email
                - password
                - confirmPassword
              properties:
                firstname:
                  type: string
                surname:
                  type: string
                email:
                  type: string
                  format: email
                password:
                  type: string
                confirmPassword:
                  type: string
      responses:
        '201':
          description: Usuário criado com sucesso
          content:
            text/plain:
              schema:
                type: string
                example: Usuário criado com sucesso
        '400':
          description: Dados inválidos ou campos faltando

  /user/token:
    post:
      summary: Gerar token JWT
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
      responses:
        '200':
          description: Token gerado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '400':
          description: Dados inválidos ou faltando

  /category/search:
    get:
      summary: Buscar categorias
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            default: 12
        - name: page
          in: query
          schema:
            type: integer
            default: 1
        - name: fields
          in: query
          schema:
            type: string
        - name: use_in_menu
          in: query
          schema:
            type: boolean
      responses:
        '200':
          description: Lista de categorias
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
                        slug:
                          type: string
                        use_in_menu:
                          type: boolean
                  total:
                    type: integer
                  limit:
                    type: integer
                  page:
                    type: integer
        '400':
          description: Parâmetros inválidos

  /category:
    post:
      summary: Criar categoria
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - slug
                - use_in_menu
              properties:
                name:
                  type: string
                slug:
                  type: string
                use_in_menu:
                  type: boolean
      responses:
        '201':
          description: Categoria criada com sucesso
        '400':
          description: Dados inválidos
        '401':
          description: Token faltando ou inválido

  /category/{id}:
    get:
      summary: Obter categoria por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Categoria encontrada
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  slug:
                    type: string
                  use_in_menu:
                    type: boolean
        '404':
          description: Categoria não encontrada

    put:
      summary: Atualizar categoria
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                slug:
                  type: string
                use_in_menu:
                  type: boolean
      responses:
        '204':
          description: Categoria atualizada com sucesso
        '400':
          description: Dados inválidos
        '401':
          description: Token faltando ou inválido
        '404':
          description: Categoria não encontrada

    delete:
      summary: Deletar categoria
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      security:
        - bearerAuth: []
      responses:
        '204':
          description: Categoria deletada com sucesso
        '401':
          description: Token faltando ou inválido
        '404':
          description: Categoria não encontrada

  /product/search:
    get:
      summary: Buscar produtos
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            default: 12
        - name: page
          in: query
          schema:
            type: integer
            default: 1
        - name: fields
          in: query
          schema:
            type: string
        - name: match
          in: query
          schema:
            type: string
        - name: category_ids
          in: query
          schema:
            type: string
        - name: price-range
          in: query
          schema:
            type: string
        - name: option[id]
          in: query
          schema:
            type: string
      responses:
        '200':
          description: Lista de produtos
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        enabled:
                          type: boolean
                        name:
                          type: string
                        slug:
                          type: string
                        stock:
                          type: integer
                        description:
                          type: string
                        price:
                          type: number
                          format: float
                        price_with_discount:
                          type: number
                          format: float
                        category_ids:
                          type: array
                          items:
                            type: integer
                        images:
                          type: array
                          items:
                            type: object
                            properties:
                              id:
                                type: integer
                              content:
                                type: string
                        options:
                          type: array
                          items:
                            type: object
                            properties:
                              id:
                                type: integer
                              title:
                                type: string
                              values:
                                type: array
                                items:
                                  type: string
                  total:
                    type: integer
                  limit:
                    type: integer
                  page:
                    type: integer
        '400':
          description: Parâmetros inválidos

  /product:
    post:
      summary: Criar produto
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - slug
                - stock
                - price
              properties:
                enabled:
                  type: boolean
                name:
                  type: string
                slug:
                  type: string
                stock:
                  type: integer
                description:
                  type: string
                price:
                  type: number
                  format: float
                price_with_discount:
                  type: number
                  format: float
                category_ids:
                  type: array
                  items:
                    type: integer
                images:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      content:
                        type: string
                options:
                  type: array
                  items:
                    type: object
                    properties:
                      title:
                        type: string
                      shape:
                        type: string
                      radius:
                        type: integer
                      type:
                        type: string
                      values:
                        type: array
                        items:
                          type: string
      responses:
        '201':
          description: Produto criado com sucesso
        '400':
          description: Dados inválidos
        '401':
          description: Token faltando ou inválido

  /product/{id}:
    get:
      summary: Obter produto por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Produto encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  enabled:
                    type: boolean
                  name:
                    type: string
                  slug:
                    type: string
                  stock:
                    type: integer
                  description:
                    type: string
                  price:
                    type: number
                    format: float
                  price_with_discount:
                    type: number
                    format: float
                  category_ids:
                    type: array
                    items:
                      type: integer
                  images:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        content:
                          type: string
                  options:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        title:
                          type: string
                        values:
                          type: array
                          items:
                            type: string
        '404':
          description: Produto não encontrado

    put:
      summary: Atualizar produto
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '204':
          description: Produto atualizado com sucesso
        '400':
          description: Dados inválidos
        '401':
          description: Token faltando ou inválido
        '404':
          description: Produto não encontrado

    delete:
      summary: Deletar produto
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      security:
        - bearerAuth: []
      responses:
        '204':
          description: Produto deletado com sucesso
        '401':
          description: Token faltando ou inválido
        '404':
          description: Produto não encontrado

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Product:
      type: object
      properties:
        enabled:
          type: boolean
        name:
          type: string
        slug:
          type: string
        stock:
          type: integer
        description:
          type: string
        price:
          type: number
          format: float
        price_with_discount:
          type: number
          format: float
        category_ids:
          type: array
          items:
            type: integer
        images:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
              deleted:
                type: boolean
              type:
                type: string
              content:
                type: string
        options:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
              deleted:
                type: boolean
              title:
                type: string
              shape:
                type: string
              radius:
                type: integer
              type:
                type: string
              values:
                type: array
                items:
                  type: string